"""Prompt builder for the Manager agent.

Constructs system and user prompts for plan generation by combining the GTD
skills file, plan-type-specific instructions, and open TODOs as JSON.
"""

from __future__ import annotations

from typing import Literal

from pydantic import TypeAdapter

from src.common.logging import get_logger
from src.common.todo_models import TodoItem

logger = get_logger(__name__)

PlanType = Literal["morning", "afternoon", "weekly-review", "weekly-plan"]

ALL_PLAN_TYPES: list[PlanType] = ["morning", "afternoon", "weekly-review", "weekly-plan"]

_TODO_LIST_ADAPTER = TypeAdapter(list[TodoItem])

# ---------------------------------------------------------------------------
# Plan-type-specific instruction templates
# ---------------------------------------------------------------------------

_PLAN_INSTRUCTIONS: dict[PlanType, str] = {
    "morning": """\
You are generating a **Morning Plan** for today.

**Purpose:** Prioritize the day and set clear intentions.

Your plan MUST include these sections in order:

1. **Summary** — A brief headline overview of the day ahead.
2. **Top 3 Priorities** — The three most important items to accomplish today. \
Use the Eisenhower matrix to identify Quadrant 1 (urgent + important) items first, \
then Quadrant 2 (important, not urgent).
3. **Quick Wins (≤ 2 min)** — Tasks that can be completed in two minutes or less. \
Per GTD's Two-Minute Rule, these should be done immediately.
4. **Next Actions by Context** — Group remaining actionable items by GTD context \
(`@computer`, `@phone`, `@home`, `@work`, `@errands`, `@anywhere`).
5. **Blocked / Waiting For** — Items waiting on someone else or blocked by a dependency.
6. **Upcoming Deadlines** — Deadlines approaching this week.
7. **Focus Statement** — A brief motivational or focusing statement to set the tone.

For every TODO item you reference, include a source link in the format: \
`[source](relative/path/to/file.md#L<line>)`.

Follow the formatting guidelines from the GTD skills reference (Section 8). \
Use checkboxes for actionable items, bold for priorities, and context tags inline.""",
    "afternoon": """\
You are generating an **Afternoon Plan** to close out the day.

**Purpose:** Re-triage, capture quick wins, and set up tomorrow.

Your plan MUST include these sections in order:

1. **Summary** — Brief progress overview for the day so far.
2. **Remaining Quick Wins** — Tasks that can be knocked out before end of day \
(≤ 15 minutes each).
3. **New Urgencies** — Any items that became urgent or were newly captured today.
4. **Defer to Tomorrow** — Items to explicitly push to tomorrow with a reason.
5. **Delegation Candidates** — Items that could be handed off to someone else.
6. **Capture** — Reminder to capture anything that emerged during the day \
but hasn't been recorded.

For every TODO item you reference, include a source link in the format: \
`[source](relative/path/to/file.md#L<line>)`.

Follow the formatting guidelines from the GTD skills reference (Section 8). \
Use checkboxes for actionable items, bold for priorities, and context tags inline.""",
    "weekly-review": """\
You are generating a **Weekly Review** — the cornerstone habit of GTD.

**Purpose:** Get clear, get current, get creative.

You will receive two lists: **open TODO items** and **items completed since \
Monday morning**. Use both to give a complete picture of the week.

Your plan MUST include these sections in order:

1. **Summary** — Headline assessment of the week.
2. **Completed This Week** — Walk through every item completed since Monday. \
Celebrate wins, note the volume and velocity of completions, and highlight \
any patterns (e.g. most completions were work-related, health tasks were neglected).
3. **Get Clear** — Walk through GTD's "Get Clear" checklist: \
process inboxes, empty your head, capture new open loops.
4. **Get Current** — Review next actions, past and upcoming calendar, \
Waiting For list, projects list, and Someday/Maybe list. \
Flag stalled projects and overdue delegations.
5. **Get Creative** — Review Horizons of Focus (Ground through 20,000 ft). \
Are current actions aligned with goals? Brainstorm new projects or improvements.
6. **Wins & Patterns** — Honest assessment of what went well and what struggled. \
Identify recurring patterns.
7. **Follow-Up Actions** — Concrete next steps generated by this review.

For every TODO item you reference, include a source link in the format: \
`[source](relative/path/to/file.md#L<line>)`.

Follow the formatting guidelines from the GTD skills reference (Section 8). \
Use `- [x]` for completed items and `- [ ]` for open items.""",
    "weekly-plan": """\
You are generating a **Weekend Review & Weekly Plan** for the coming week.

**Purpose:** Close out the weekend and set intentions for the week ahead.

You will receive two lists: **open TODO items** and **items completed over \
the weekend (Saturday and Sunday)**. Use the completed items to review the \
weekend before planning the week.

Your plan MUST include these sections in order:

1. **Weekend Review** — Summarize what was accomplished over the weekend. \
Walk through each completed item, celebrate wins, and note any loose ends.
2. **Summary** — Theme or focus area for the coming week, informed by the \
weekend review and remaining open items.
3. **Top 3-5 Weekly Priorities** — The most important outcomes for the week. \
Use the Eisenhower matrix to prioritize.
4. **Day-by-Day Allocation** — Rough allocation of goals and tasks to specific \
days (Monday through Friday). Consider context and energy patterns.
5. **Active Projects** — List each active project with its next action. \
Every project MUST have at least one next action.
6. **Quadrant 2 Blocks** — Reserve specific time blocks for important-but-not-urgent \
work (strategic planning, skill-building, health).
7. **Potential Conflicts** — Flag any overcommitments or scheduling conflicts.
8. **Someday/Maybe Check** — Items from Someday/Maybe worth activating this week.

For every TODO item you reference, include a source link in the format: \
`[source](relative/path/to/file.md#L<line>)`.

Follow the formatting guidelines from the GTD skills reference (Section 8). \
Use checkboxes for actionable items, bold for priorities, and context tags inline.""",
}


def get_plan_instructions(plan_type: PlanType) -> str:
    """Return the plan-type-specific instruction text.

    Raises:
        ValueError: If *plan_type* is not a recognised plan type.
    """
    instructions = _PLAN_INSTRUCTIONS.get(plan_type)
    if instructions is None:
        valid = ", ".join(ALL_PLAN_TYPES)
        msg = f"Unknown plan type {plan_type!r}. Valid types: {valid}"
        raise ValueError(msg)
    return instructions


def build_system_prompt(skills_content: str, plan_type: PlanType) -> str:
    """Build the system prompt by combining GTD skills and plan instructions.

    Args:
        skills_content: The full text of the GTD skills file.
        plan_type: Which plan type to generate.

    Returns:
        The assembled system prompt string.
    """
    instructions = get_plan_instructions(plan_type)
    return f"{skills_content}\n\n---\n\n{instructions}"


def build_user_prompt(
    open_todos: list[TodoItem],
    completed_todos: list[TodoItem] | None = None,
) -> str:
    """Build the user prompt containing open TODOs as JSON.

    Args:
        open_todos: List of open TODO items from the store.
        completed_todos: Optional list of recently completed TODO items
            (e.g. completed since Monday for a weekly review).

    Returns:
        The user prompt string.
    """
    parts: list[str] = []

    if open_todos:
        todos_json = _TODO_LIST_ADAPTER.dump_json(open_todos, indent=2).decode()
        parts.append(
            f"Below are the current open TODO items ({len(open_todos)} total) "
            f"from the user's notes.\n\n"
            f"```json\n{todos_json}\n```"
        )
    else:
        parts.append(
            "There are currently **no open TODO items** in the store.\n\n"
            "Generate a plan that acknowledges the empty inbox and suggests "
            "proactive actions: review Someday/Maybe items, do a mind sweep "
            "to capture new commitments, or focus on Quadrant 2 strategic work."
        )

    if completed_todos:
        completed_json = _TODO_LIST_ADAPTER.dump_json(completed_todos, indent=2).decode()
        parts.append(
            f"\n\nBelow are the recently completed TODO items "
            f"({len(completed_todos)} total).\n\n"
            f"```json\n{completed_json}\n```"
        )

    return "\n".join(parts)
